### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by xuanzhiqiang** [Omooo/VirtualApplication#1]
👍

**Comment by Omooo** [comment]
谢谢支持，共同进步～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Omooo/VirtualApplication"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 晚上6:22
收件人:&nbsp;"Omooo/VirtualApplication"<VirtualApplication@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Omooo/VirtualApplication] 大佬 (#1)





 
👍
