### ISSUE TITLE
关于宿主和插件加载资源问题

### ISSUE THREAD

**Issue by hyandroid** [Omooo/VirtualApplication#2]
大佬好，请教一个问题，用这种代理方式启动插件apk，用宿主的context加载插件资源的时候，比如

```
        findViewById(R.id.myView).setBackgroundColor(getResources().getColor(R.color.color_plugin));

```
为什么能正确取到插件的资源，不会取到宿主apk对应的资源id呢？ 
因为两个apk是单独打包的，资源id索引arsc肯定会有冲突情况，却能互不影响
这一块不是很理解。

**Comment by Omooo** [comment]
因为这个 getResources 是我已经重写的方法，你可以点进去看一下就知道了。

**Comment by Omooo** [comment]
实际上就是：PluginManager.getInstance(this).getResources()，他就是插件的资源了。

**Comment by hyandroid** [comment]
嗯嗯，了解了。以这种方式启动插件，会有些其他的隐藏问题吗？如果用在项目中，会有哪些需要注意的地方呢？

**Comment by Omooo** [comment]
这种方式是把插件的 dex 文件合并到了 app 的 dexElementList 里面了，所以如果有重复的类（类的全限定名一样）就 GG 了。

**Comment by Omooo** [comment]
推荐一哈我的 Android 学习笔记撒：https://github.com/Omooo/Android-Notes
对你 Android 面试也有很大帮助，可以康康～

**Comment by hyandroid** [comment]
多谢

**Comment by hyandroid** [comment]
还有个问题，我看插件Activity的生命周期都是空实现，而且没有被调用到，那么插件Activity的生命周期怎么监听呢？

**Comment by Omooo** [comment]
其实就是调用 ProxyActivity 他的生命周期函数的，可以看一下他的 onCreate 方法，其实就是把插件的 Activity 强转成 ActivityInterface 这个接口来做的。

**Comment by hyandroid** [comment]
懂了
